### ISSUE TITLE
Why no Obsidian in Connected Accounts?

### ISSUE THREAD

**Issue by AndyLiu9** [getmatterapp/obsidian-matter#1]
Just as the title, I can’t find Obsidian in my Connected Accounts.
![3337336E-6AAD-4960-9142-B3F42DB2DCFE](https://user-images.githubusercontent.com/88693956/145424547-4dc1ce13-0cc9-460b-8c41-28d38a6951da.png)

**Comment by hunterclarke** [comment]
Hey Andy!

The Obsidian connected account will be released in an upcoming iOS release (hopefully today). We're waiting on Apple. In the meantime, if you go to settings > connect web extension, scanning the QR should still work.

I'll let you know when the knew iOS release is in the app store.

**Comment by AndyLiu9** [comment]
Wow so efficient you are! Thanks a lot!

**Comment by AndyLiu9** [comment]
Amazing! Thanks!
