### ISSUE TITLE
Items removed from Queue and Highlights still sync

### ISSUE THREAD

**Issue by philoserf** [getmatterapp/obsidian-matter#13]
Despite removing items from the Queue and the Highlights and deleting those items in the Vault. Items continue to reappear at each Matter sync.

**Comment by Medenor** [comment]
I have the same issue

**Comment by philoserf** [comment]
I have found a workaround.

I had to go to the web interface to Matter and remove my highlights.

It may be a matter of the iOS app not being in sync with the rest of the new system at the time I was using it.

**Comment by hunterclarke** [comment]
Hi @philoserf, looks like there's a bug on iOS that's preventing you from seeing all of your highlights in the highlights list. Once that is resolved, deleting the highlight would resolve this issue. Is that right? Or am I missing something else?

**Comment by philoserf** [comment]
I found two workarounds
- remove highlights (any interface)
- from highlights, add to queue, delete from queue

**Comment by hunterclarke** [comment]
Resolved in 1.1.3

https://github.com/getmatterapp/obsidian-matter/commit/610f2c333edf71dc3193025e5f49ca2d634515d2
