### ISSUE TITLE
Feature request:  highlights formatted as quotes

### ISSUE THREAD

**Issue by JoelAnderson-UU** [getmatterapp/obsidian-matter#14]
Thanks so much for this plugin! Small feature request:  I'd very much appreciate the option to have the highlights marked as a list o quotes, so that it's clear that the text in the highlights are not my own words.

### Highlights
> - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

> - Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Thanks for considering this as an option!

**Comment by hunterclarke** [comment]
Hey @JoelAnderson-UU!

This would be supported via the templating project outlined [here](https://github.com/getmatterapp/obsidian-matter/issues/4). I would suggest following that topic and the upcoming development. Thanks for the feedback!
