### ISSUE TITLE
[FEATURE] Disable Sync at Startup

### ISSUE THREAD

**Issue by levifig** [getmatterapp/obsidian-matter#16]
Hey 👋 

As it stands, this plugin syncs at Obsidian startup, no matter what. I would like to disable that as it's very obviously slowing down app start which, in the case of Obsidian, it's something that happens quite frequently, unfortunately (being a web view and all).

Thank you for this and the great product! :3

--LF

**Comment by ryangomba** [comment]
Agreed. I believe there are two considerations here:
1. How does this plugin running at startup affect performance?
2. How does seeing a notification at startup distract from the core experience? Something https://github.com/getmatterapp/obsidian-matter/issues/33 touches on

Either way, I think it would be nice to enable or disable syncing at startup based on user preference.

**Comment by hunterclarke** [comment]
Released in 1.1.4 thanks to @ryangomba!
