### ISSUE TITLE
sync error

### ISSUE THREAD

**Issue by adamyang18** [getmatterapp/obsidian-matter#18]
tried restarting OB and reinstall the extension for several times, Sync cannot work. the error message in development console:

plugin:matter:2572 TypeError: Cannot read properties of null (reading 'children')
    at MatterSettingsTab.eval (plugin:matter:2568:25)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:matter:53:24)

**Comment by hunterclarke** [comment]
Thanks for the report. Looking into this today 👍

**Comment by hunterclarke** [comment]
Hey @adamyang18 I just released version 1.0.6 that should resolve this issue. Let me know if you're still having issues.

**Comment by adamyang18** [comment]
Hi @hunterclarke thank you so much for the quick follow-up. 

I updated, still nothing was synced. and I uninstall and restart OB and installed it again, but still nothing. 

But this time, there is no information in the Developer Console.

**Comment by hunterclarke** [comment]
@adamyang18 hrm so I fixed the error in the console but it didn't resolve the sync issue... 

Are you seeing requests out to `api.getmatter.app`?

**Comment by hunterclarke** [comment]
For the record, on a fresh install I'm able to install, authenticate, and sync. So I'm having trouble replicating the specific issue you're experiencing.

**Comment by adamyang18** [comment]
I used another Vault to do a fresh install. The same problem. Is it any problem with my Matter account? My Matter account user name: poweremail@gmail.com

Could you please take a look?

**Comment by hunterclarke** [comment]
Taking a look now. I'll email you directly with what I find
