### ISSUE TITLE
Adding dates to titles

### ISSUE THREAD

**Issue by anvimea** [getmatterapp/obsidian-matter#19]
Hi,

Big fan of Matter, and as someone who's been using the plugin since day 1, I'm very glad at the little tweaks that have over time made the plugin much more fluid.

Like many Obsidian users, I append some of my files with prefixes via Obsidian's native Zettelkasten plugin - now called "Unique note creator". This adds a prefix in the form of YYYYMMDDHHMM to the file title, preceding the title.

I'd love it if this was automatically used for Matter's imports, perhaps either as a:
-  Toggleable option in the settings
- Via a setting that allowed us to manually format imported titles.

**Comment by hunterclarke** [comment]
Hey @anvimea, I'll think on this. On first glance, this might be a tricky one for us to handle on your behalf. It may be something we enable when we implement templates for syncing. I'll leave this open and keep you posted!

**Comment by hunterclarke** [comment]
I think if a solution for this is created, it would be a part of the templating project outlined [here](https://github.com/getmatterapp/obsidian-matter/issues/4). I would suggest following that topic and the upcoming development. Thanks for the feedback!
