### ISSUE TITLE
API doesn't return the highlight so syncing doesn't work. 

### ISSUE THREAD

**Issue by basilaiman** [getmatterapp/obsidian-matter#22]
Hello! 

I just installed the plugin and It doesn't sync. The folder is just empty. 
I tried to inspect the API returned results using developer tools. It doesn't return the anything. 
```json
{
  "id": "4",
  "feed": [],
  "next": null,
  "previous": null,
  "current_profile": "emitted for privary"
}
```

**Please Note** that I have highlights in the app.

**Comment by hunterclarke** [comment]
@basilaiman I'm so sorry, I must have missed this. Are you still experiencing the issue?

**Comment by QuigonJohnn** [comment]
Sync doesn't work at all for me either. I'm a new user with just a few links saved, but nothing shows up in Obsidian.

**Comment by basilaiman** [comment]
@hunterclarke Yes, I just confirmed now. 
I uninstalled the plugin, reinstalled again and still not working.

**Comment by hunterclarke** [comment]
Thanks @basilaiman. Looking into it now.

**Comment by hunterclarke** [comment]
Assuming your username is the same in Matter, I'm not seeing any annotations (highlights or notes) on your profile. Would you mind sharing a screenshot of a highlight you would expect to sync?

**Comment by basilaiman** [comment]
Thanks. This is screenshot from my iOS app [here](https://ibb.co/JpyZvcy) .

It's also worth to mention that I don't see the highlights on my web app. But I see them on my iOS app.

I tried to add a highlight from web app. It succeed and showed on iOS but still now showing on web

**Comment by basilaiman** [comment]
@hunterclarke Let me know if you need more info from my side ✌️

**Comment by hunterclarke** [comment]
@basilaiman this may be an instance of https://github.com/getmatterapp/obsidian-matter/issues/32. It's an issue I'm going to work on next (it's quite involved at the api level).

Are you only taking article level notes? Or are you highlighting the content within the articles? Right now, and this will change, only highlights created within the article will sync to Obsidian.

**Comment by hunterclarke** [comment]
@QuigonJohnn 
>  Sync doesn't work at all for me either. I'm a new user with just a few links saved, but nothing shows up in Obsidian.

Only content highlights and notes sync to Obsidian. You'll have to create some highlights in order to get sync to work.

**Comment by basilaiman** [comment]
I didn't know It was possible to take highlight notes, I was only taking article level notes. 

I tried highlight notes and it worked well! 

Thank you @hunterclarke

**Comment by hunterclarke** [comment]
Awesome! I'll keep you posted with the article level note functionality.
