### ISSUE TITLE
Preserving newlines in highlight template

### ISSUE THREAD

**Issue by TSSlade** [getmatterapp/obsidian-matter#34]
Given a highlight template of
```
> {{text}}
{% if note %}
- **Note**: {{note}} {{'' | nl2br}}
{% endif %}
```
I wind up with highlights `2...n` slightly nested under the note associated with highlight `1`. I would like to include a newline at the end of the template, but I can't figure out how to do so.

- **Q. 1:** Is this plugin in fact using the nunjucks library for the templating?
- **Q. 2:** Can I somehow pass in config arguments for nunjucks such as `preserve_linebreaks == true` (or whatever the equivalent is)?

**Comment by TSSlade** [comment]
I was able to tweak the template and get the desired outcome by moving it to

```
> {{text}}
{% if note %}
- **Note**: {{note}}
  
{% endif %}
```
...but my questions remain in general, so I'll wait for them to be answered and then close.

**Comment by hunterclarke** [comment]
> Q. 1: Is this plugin in fact using the nunjucks library for the templating?

Yes it is.

> Q. 2: Can I somehow pass in config arguments for nunjucks such as preserve_linebreaks == true (or whatever the equivalent is)?

We use a common configuration for all rendering, so you would have to double check that injecting config arguments wouldn't affect the rest of the rendered note. I'd like to avoid adding complexity to the configuration if at all possible. Seems like you landed on a pretty simple solution to the overall issue :)
