### ISSUE TITLE
Date format info

### ISSUE THREAD

**Issue by Calorion** [getmatterapp/obsidian-matter#39]
There is no information on how dates are formatted, either in the plugin interface or (surprisingly) at https://mozilla.github.io/nunjucks/templating.html. 

The existing template looks like `published: {{published_date|date("YYYY-MM-DD")}}`; what are the formatting rules here?

**Comment by hunterclarke** [comment]
We use [moment](https://momentjs.com/docs/#/displaying/), for formatting. I agree this needs to live in the docs, but I'm not entirely sure where. The description boxes are not great for showing template documentation.

I'll think on it and make some changes.
