### ISSUE TITLE
Syncing and new highlights

### ISSUE THREAD

**Issue by Calorion** [getmatterapp/obsidian-matter#42]
What happens when I make more highlights on an article in Matter after I've synced it to Obsidian? Will it overwrite any changes I've made in the Obsidian note? Make a new copy? Do nothing?

**Comment by hunterclarke** [comment]
@Calorion it will append the new highlights to the bottom of the note. So if you've made changes, those will not be impacted.

**Comment by Calorion** [comment]
So I'm not sure this is working right. If I make a change to the text of my highlights in Matter, and resync in Obsidian, the text of my note in Obsidian does not change. I have to delete and resync, and then it works.

**Comment by davebhc71** [comment]
The comment made by @Calorion above is STILL happening. The sync issue has NOT been corrected and new highlights are NOT appended to the ‘original’ sync. **So I would suggest revisiting this issue since NOW Matter is a subscription App that is NOT working as advertised with Obsidian.**

**Comment by hunterclarke** [comment]
Taking a look at this again given the latest discussion:

> So I'm not sure this is working right. If I make a change to the text of my highlights in Matter, and resync in Obsidian, the text of my note in Obsidian does not change. I have to delete and resync, and then it works.

The Matter plugin **will not modify** (edit or remove) any text already in a note on sync. Once a highlight has been synced, the plugin will disregard any change to that highlight. So this means:
1. If you delete a highlight in Matter, the highlight will not be removed from Obsidian.
2. If you modify a note in Matter after it has synced to Obsidian, the changes will not be reflected in Obsidian.

If you want to modify anything about how a highlight or note appears in Obsidian, you should delete the original highlight in Matter, recreate it as you would like, then sync to Obsidian (and remove any outdated highlight).

Obsidian gives us fairly limited editing capabilities. Which means we have to be careful about accidentally overwriting any data in the system. So we treat it as an append-only document. It's not an ideal user experience (trust me, I know), but it's the most seamless we can come up with given the constraints of the Obsidian editor.

Let me know if you have any other comments/questions.

**Comment by Calorion** [comment]
I am now extremely confused. You have said, twice, in two different contexts, 

>The matter plugin appends highlights made after an initial sync to the bottom of the Obsidian note.

Does it do that or not? Because that is precisely what is not happening for me.

**Comment by hunterclarke** [comment]
That is how it should work, yes. Can you email me an example if it's not working for you? I'm hunter at getmatter dot com.

Sorry for the back and forth! This is likely my fault for misinterpreting "note" in your message above. I thought you were referring to a Matter note, but now I see you were referring to an Obsidian note. Confusing indeed!

**Comment by davebhc71** [comment]
Hey guys….I hesitate to comment here in your posts, but I added a reply in #49 that works for me…..and therefore solves the sync issue as far as I understand it……Thanks Hunter. Hope you guys can work out……your issues. 😉

**Comment by Calorion** [comment]
Well, yes, that definitely works, as I said above, but does not solve the issues. 

Unfortunately, in the interim Matter has gone paid, and I'm not, at this point, going to pay $60/yr to help troubleshoot this issue or see if it still exists.
