### ISSUE TITLE
Future of plugin and Matters business plan

### ISSUE THREAD

**Issue by 0ge** [getmatterapp/obsidian-matter#45]
Hi,

I was reading the [business model](https://hq.getmatter.com/patron) for Matter. It states the following (emphasis mine):

 > Matter Premium will cost **$8/month or $60/year** and will include features that go beyond the basics: HD text-to-speech, fluid highlighting and note-taking, **integrations**, full-text search, options to personalize Matter, and priority support.

Just to clarify, that means that from January 15, 2023 integration will stop working for free-tier users?

**Comment by hunterclarke** [comment]
Yes, that's the plan
