### ISSUE TITLE
Sync favourited articles

### ISSUE THREAD

**Issue by EllyLoel** [getmatterapp/obsidian-matter#46]
Often I want to sync an article without highlighting any specific part of the article, it would be nice if there was a way to sync an article without highlighting, my first thought was favourites might be a good way of doing it.

**Comment by hunterclarke** [comment]
Hi @EllyLoel, thanks for the comment. Something like that seems out of scope for this plugin. This is primarily focused on making your highlights + notes transferrable.

We're looking into opening up our API for developers. When that happens, we're hoping others can fill in alternate use cases like yours!
