### ISSUE TITLE
Fail to load Matter + duplicated sync notes

### ISSUE THREAD

**Issue by YannickTemplay** [getmatterapp/obsidian-matter#5]
Today I got a "fail to load matter" plugin error.

I tried to reactivate the plugin. Did not work.

I uninstalled and reinstalled it. It worked... but now all my Matter notes are synced... twice.

Fortunately, I had only a few but if I was really using Matter for serious reading and I had hundreds of notes that would be very bad. If every time the plug-in gets re-installed everything gets duplicated...

**Comment by YannickTemplay** [comment]
In fact, it seems that the double sync still goes on, it's not just the initial sync as I thought. 
Like if the API is used twice or something.

**Comment by beala** [comment]
I am also getting duplicated notes. I did not re-install the plugin anywhere. I do use obsidian + icloud sync across multiple devices.

When I try to delete the duplicated notes, they reappear on sync. Let me know what additional information I can provide.

I'm currently on plugin version 1.0.1.

**Comment by YannickTemplay** [comment]
I am using obsidian sync too on two devices (Mac + iPhone) with all plugins sync on both devices. Maybe the sync is done twice indeed.

**Comment by hunterclarke** [comment]
@YannickTemplay thanks for the issue report. I also ran into some of this behavior over the holidays. I believe multiple device sync is the root of the issue.

The basic concern is that Matter will sync on launch. However, if  Obsidian sync (or any other sync provider) runs concurrently, the two processes step on each other's toes.

Personally, I've disabled Matter on my phone in the meantime.

With the holidays behind us, I'm going to try and figure out a long term solution soon.

**Comment by hunterclarke** [comment]
@YannickTemplay @beala The latest release https://github.com/getmatterapp/obsidian-matter/releases/tag/1.0.2 has a fix that should help with the duplicated notes. Let me know if you still have some issues. I'm also monitoring closely on my own devices.

**Comment by YannickTemplay** [comment]
Many thanks but I have stopped using Matter right now so I won't be able to test.

**Comment by hunterclarke** [comment]
I haven't seen any instances of duplicates since release. I'm going to close this for now. Please feel free to comment if you still have issues.
