### ISSUE TITLE
Show notebook in core note

### ISSUE THREAD

**Issue by iamrobmat** [getmatterapp/obsidian-matter#57]
I wanted to use notebook in matter app section to store translations of my highlights. Is there an option to get that outside of metadata template since those are long?

PS. I've edited metadata in plugin setting so they match yaml properties. See below.

I've tried to move the notebook into highlight template but it does not showup.

Metadata template:
---
url: {{url}}
{% if author %}
author: {{author}}
{% endif %}
{% if published_date %}
published date: {{published_date|date("YYYY-MM-DD")}}
{% endif %}
{% if tags %}
tags: matter-highlights {% for tag in tags %}{{tag | replace(' ', '_')}}{% if not loop.last %} {% endif %}{% endfor%}
{% endif %}

---

Highlight template:

* {{text}}
{% if note %}
note: {{note}}
{% endif %}
{% if note %}
  * **Note**: {{note}}
{% endif %}

**Comment by hunterclarke** [comment]
I need a little more information. 
1. Are you storing the translations as a "note" on the highlight?
2. Your highlight template has `{{note}}` twice. Is that intentional?

**Comment by iamrobmat** [comment]
1. In the iOS Matter app there's the thing called "Notebook" where you can add extra text besides your highlight. This is the place where I've tried to put translations.
2. It has twice because I have copied that exact part from "Metadata Template" section.

**Comment by hunterclarke** [comment]
Based on what I'm seeing, there shouldn't be anything from the notebook appearing in the metadata section. Would you mind sharing a screenshot of the problem?

**Comment by iamrobmat** [comment]
You're correct, based on the code I've provided above we won't find anything from the notebook in the metadata section. That is because I've moved this element below from metadata section to highlight section. This was originally in metadata section and was showing text from notebook. I am no programmer so thought this would work :)

{{text}}
{% if note %}
note: {{note}}

This is how it looked like before moving this note snippet to highlight. My goal is to have this text from notebook as core part of note, not in metadata to reuse it. 

<img width="618" alt="Zrzut ekranu 2023-08-24 o 11 07 28" src="https://github.com/getmatterapp/obsidian-matter/assets/35330460/81502587-ab06-4c39-abe2-08c9475ca89f">

**Comment by hunterclarke** [comment]
Ah I see, you're setting the article level note to the translation. Since that's not a part of highlights, it's not possible to move that to the highlights section. It's a property of the article and (in most cases excluding yours) would be most useful as a part of the metadata.

I don't think we're going to change this behavior at this point. However, I do want to expand our templating to be a little more flexible. Then you can move it where you like. I'll let you know when we decide to take that on. 

Let me know if you have any other questions/suggestions!
