### ISSUE TITLE
[Feature Request] Allow files to be refiled to new location

### ISSUE THREAD

**Issue by JamesHWade** [getmatterapp/obsidian-matter#8]
Hello,

I really like this plugin! I typically add comments to my notes and then move them to a new folder. This results in the files being re-synced to the original location. I would like to be able to move files around without re-syncing them.

The [hypothesis plugin](https://github.com/weichenw/obsidian-hypothesis-plugin) has this behavior.

Thanks again for creating this plugin! It's great.

**Comment by ChristinWhite** [comment]
This is the way I prefer to work as well, it would be awesome to have this as an option.

**Comment by hunterclarke** [comment]
Thanks for the feature request! This has been requested a number of times on Twitter so it's on the roadmap. I'm collecting a bunch of bugs/features that we want to implement in the next major release of the plugin and this will definitely be included.

**Comment by siainbuletin** [comment]
Could maybe be done by stopping sync for articles that are not currently being read, and are archived, because if I want to move them out of the Matter folder, they appear back in.

**Comment by martincodez** [comment]
> Could maybe be done by stopping sync for articles that are not currently being read, and are archived, because if I want to move them out of the Matter folder, they appear back in.

Agree with above — Right now I believe I need a seperate vault to even use this and get notes into my ecosystem, appreciate you taking a look at this critical feature

**Comment by JoseEchave** [comment]
+1 to this request. Would be really helpful and a great addition to an already amazing plugin!

**Comment by hunterclarke** [comment]
Hi this has been released in v1.0.4. After you upgrade, disable "Always Recreate Missing Files" in the Matter plugin's settings page.
